### ISSUE TITLE
high ram use on `walker --gapplication-service`

### ISSUE THREAD

**Issue by zspher** [abenz1267/walker#121]
**Describe the bug**
high ram use on `walker --gapplication-service`

whenever i run walker with the service on, ram just keeps increasing without decreasing

**Version**
0.7.7

**Minimal Config**
Provide a minimal config to reproduce the bug.

```nix
  programs.walker = {
    enable = true;
    config = {
      ignore_mouse = true;
      activation_mode.labels = "123456789";
      activation_mode.use_alt = true;

      disabled = ["finder" "runner" "windows"];
      list.max_items = 20;
    };
  };
```

**To Reproduce**

1. run `walker --gapplication-service`
2. keep running `walker` and type something
3. do the above repeatedly

**Expected behavior**
ram should decrease and stay at some default level after `walker` is ran

**Screenshots**
spammed walker repeatedly till 1Gb ram use; checked with `btop`
![Screenshot_2024-08-27-18-13-23](https://github.com/user-attachments/assets/0f6f5b82-271e-4173-90e2-bb681ca9d574)

**Desktop**

- OS: `Linux 6.6.47, NixOS, 24.11 (Vicuna), 24.11.20240821.c374d94`
- DE: `Hyprland v0.42.0`

**Additional context**

**Comment by abenz1267** [comment]
So far I've identified the 2 issues causing the memory leaks: one is caused by the calc module, the other one is most likely caused by the used GTK library, see https://github.com/diamondburned/gotk4/issues/126.

**Comment by quadbyte** [comment]
I'm also seeing very high ram usage when trying out the "finder" modules.
It seems the indexing is never releasing memory leading up to 21GB of Ram usage.
![image](https://github.com/user-attachments/assets/a6c3827d-60be-4800-9609-2a09cf44b6cc)

It is no big deal for me  as I don't plan on using the Finder features. I'll disable it in the config.

**Comment by abenz1267** [comment]
> I'm also seeing very high ram usage when trying out the "finder" modules. It seems the indexing is never releasing memory leading up to 21GB of Ram usage. ![image](https://private-user-images.githubusercontent.com/2170677/381570536-a6c3827d-60be-4800-9609-2a09cf44b6cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTcxODgsIm5iZiI6MTczMDI5Njg4OCwicGF0aCI6Ii8yMTcwNjc3LzM4MTU3MDUzNi1hNmMzODI3ZC02MGJlLTQ4MDAtOTYwOS0yYTA5Y2Y0NGI2Y2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMTQwMTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDkyZGQxMTcxYWE0OGQyNjRiMzBlYWMwMWQxODljMDFiZDEwMWM2Y2E5Zjc2OTJlZWM4MGQ2NTNlY2E1ZWExNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ombKOu4gV_-lngBAg-_G0x7YXmQKtwVIMBGCVzttfTE)
> 
> It is no big deal for me as I don't plan on using the Finder features. I'll disable it in the config.

Should be fixed in git.

**Comment by rkunschke** [comment]
It seems to be still an issue. Every time I open walker the ram usage increases. About 3 mb every time I open it. 
It should be fixed in the point-release versions as well I guess?

**Comment by abenz1267** [comment]
[nothing i can do anything about. it has to be fixed in GOTK4, there's an open issue but the maintainer is.... busy? I ](https://github.com/diamondburned/gotk4/pull/161)

**Comment by rkunschke** [comment]
> [diamondburned/gotk4#161](https://github.com/diamondburned/gotk4/pull/161) => that's the PR. Sadly the maintainer is... busy? Doesn't care? I don't know. I'd assume busy.

Okay thank you. I gave that PR a thumbs up and subscribed it. Till than I am happy to have a big swap-file :D
