### ISSUE TITLE
[BUG] apps under ~/.local/share/applications not shown anymore

### ISSUE THREAD

**Issue by ad-on-is** [abenz1267/walker#177]
I just updated to 0.10.16-git by building it myself, and .desktop files under ~/.local/share/applications are not shown.

Is there anything I'm missing?

Edit: setting {"applications": "enabled"=false} fixes it.

**Comment by abenz1267** [comment]
Please provide a minimal config to reproduce this.

**Comment by ad-on-is** [comment]
> Please provide a minimal config to reproduce this, as i can't reproduce this.

I just edited my question. Setting applications -> enabled -> false in the config solves it. Maybe some documentation on what these settings do would be helpful.

**Comment by abenz1267** [comment]
There is no such setting `applications.enabled`. Hence I'm asking about the minimal config for reproduction.

**Comment by ad-on-is** [comment]
if they're enabled, it does not work... but if they are disabled, then they do work.

**Comment by abenz1267** [comment]
Try setting `applications.show_generic` to `true`. 

This should default to true, if actions are disabled... I'll "fix" that.

**Comment by abenz1267** [comment]
Nah, that's not it. I'll investigate further.

**Comment by abenz1267** [comment]
should be fixed in git.

**Comment by ad-on-is** [comment]
Yep! works now... with show_generic: false and actions.enabled: true

However, I still don't know what these settings are for. Could you write some documentation please? 

I only found about this issue, because I copy&pasted the modified actions from another issue, since walker wouldn't launch otherwise.

**Comment by abenz1267** [comment]
Yeah, I'm aware documentation could be better. I've already started a new documentation with gitbook, at one point it'll actually be out.

For your question:

Desktop files in linux can have `actions`, f.e. Firefox has different actions like: `new window` or `new private window`, while the generic entry is just `Firefox`.

So with the actions and `show_generic`, you can define what exactly gets shown to you.
