### ISSUE TITLE
Many icons missing?! 

### ISSUE THREAD

**Issue by RoccoRakete** [abenz1267/walker#25]
There are many icons missing in the applications list. I don't know if it has anything to do with these errors?! 

![Screenshot_29-03-24_12-13](https://github.com/abenz1267/walker/assets/44879342/19a502c8-b938-4f37-bf5b-ae8a208d9235)

**Comment by abenz1267** [comment]
You need to provide more information:

- What's your GTK4 theme? 
- What's your icon theme?
- example *.desktop file of an app with missing icon

**Comment by RoccoRakete** [comment]
- GTK4 Theme is Catppuccin Mocha
- Icon Theme is Morewaita
- .desktop file example: https://pastebin.com/iwAAU6qc

If it's relevant, anyrun and wofi are working fine. 

Let me know if you need anything else!

**Comment by abenz1267** [comment]
Both anyrun and wofi are GTK3. Walker is GTK4.

I've installed the GTK theme and icon theme.. also installed boxbuddy and geary. No problems.

I've changed the way icons are loaded in order to catch errors... can you checkout the latest version, start via terminal and see if there's an icon-related error showing up?

This issue only seems to affect Nix users... on Arch stuff is fine.

**Comment by RoccoRakete** [comment]
Not fixed unfortunately. 

![Screenshot_29-03-24_14-40](https://github.com/abenz1267/walker/assets/44879342/aec3cee3-b623-4033-ab47-31cdce70b2cf)

**Comment by abenz1267** [comment]
I've just pushed an update letting you explicitly set an icon theme... can you try that? I don't know what kinda problem nix and gtk4 have with icons....

```json
icons: {
"theme": "<theme>"
}
```

**Comment by RoccoRakete** [comment]
Still the same. 

![image](https://github.com/abenz1267/walker/assets/44879342/7f36bde1-a324-4d95-8b61-ec9f9ded805e)

**Comment by abenz1267** [comment]
Ok, can u do this for me? Put the following into `example.c`:

```c
#include <gtk/gtk.h>

static void
activate (GtkApplication* app,
          gpointer        user_data)
{
  GtkWidget *window;
  GtkWidget *icon;
GtkWidget *box;

    icon = gtk_image_new_from_icon_name ("org.gnome.Geary");

  window = gtk_application_window_new (app);

box = gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
  gtk_window_set_child (GTK_WINDOW (window), box);
    gtk_box_append (GTK_BOX (box), icon);

  gtk_window_set_title (GTK_WINDOW (window), "Window");
  gtk_window_set_default_size (GTK_WINDOW (window), 200, 200);
  gtk_window_present (GTK_WINDOW (window));
}

int
main (int    argc,
      char **argv)
{
  GtkApplication *app;
  int status;

  app = gtk_application_new ("org.gtk.example", G_APPLICATION_DEFAULT_FLAGS);
  g_signal_connect (app, "activate", G_CALLBACK (activate), NULL);
  status = g_application_run (G_APPLICATION (app), argc, argv);
  g_object_unref (app);

  return status;
}
```

compile it via: `gcc $( pkg-config --cflags gtk4 ) -o example example.c $( pkg-config --libs gtk4 )` .

Run `./example`.

This should show the geary icon.

**Comment by RoccoRakete** [comment]
Sure. But I'm getting this.

![Screenshot_29-03-24_19-01](https://github.com/abenz1267/walker/assets/44879342/70a8429a-7ebc-4d9b-ac02-64a7f2ed16a0)

**Comment by abenz1267** [comment]
Yeah, ok... for me this is good news: the issue is not related to Walker. I'm sorry.

Guess you need to ask Nix people why it's broken.

Closing, as it's not related to Walker.

**Comment by RoccoRakete** [comment]
Okay, so maybe @diniamo knows this? Since he packaged it for nix?

**Comment by diniamo** [comment]
It shouldn't have anything to do with the Nix package. I have no idea.

If walker uses the builtin methods of gtk, or some xdg library, I can't help you.

**Comment by abenz1267** [comment]
@RoccoRakete you should open an issue with Nix (github? their forum?) and provide the little C example from above.

**Comment by RoccoRakete** [comment]
Yes, I already opened an issue with this discussion linked.

**Comment by abenz1267** [comment]
Can you link it here so i can follow? There'll be more users and having a place to point them to would be good.

**Comment by RoccoRakete** [comment]
It's over at the nixOS Discord ID is: 1223334083556409555
